<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="WhatsNew.aspx.cs" 
Inherits="FlyerMe.WhatsNew" Theme="" %>
<asp:Content ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="text-content">
        <div class="content">
            <h1>What's New</h1>
        	<p>Welcome to the exciting new release of <%= clsUtility.SiteBrandName %>. We have added many new features that will make it easier and fun to design and send email campaigns to other real estate professionals in your area. And, you will be able to post your flyers on popular real estate websites like Zillow, Trulia and more, automatically so that prospective buyer can see your listings!</p>
            <h6 class="left">Here’s a look at some of the new features in this release:</h6>
            <ul>
                <li>We&rsquo;ve made it even easier to create a flyer (if that is even possible!) by reducing the number of steps to 5. Or better yet, create a flyer in minutes.</li>
                <li>Selecting the state and market are now on one easy page to navigate. Check it out for yourself.</li>
                <li>Navigation between steps is way easier now as we now let you simply click on the step you want to go to, forward and backwards. If you are a little old school and like the old way, we still let you use the &ldquo;previous&rdquo; and &ldquo;next&rdquo; button at the bottom of the page.</li>
                <li>Step 3 (Flyer Content) is where the new features get real exciting! We wanted you to create a flyer with as little typing as possible and have access to even more cool features. First, we added Property Type &amp; Category fields that we use when posting your flyers to popular real estate sites like Craigslist, Trulia, Zillow and others.</li>
                <li>Also in Step 3, we automatically fill in the property information (with the help of our friends at Zillow!) once you enter the property address.</li>
                <li>Tired of thinking about all the property highlights and typing them in? We now give you easy to use check boxes to make your life much easier.</li>
                <li>The net result is that you are able to add the flyer content in minutes and still get the same great <%= clsUtility.SiteBrandName %> templates and layout.</li>
                <li>Okay, you are now ready to pay for your flyer. But wait, you want to create another one before you pay for it! Prior to this release, you would have to pay for the current flyer and then go back and create and pay for the next one. We now let you save as many flyers as you want and create new ones and pay for them all at the end. When you go to the payment screen, flyerus will look in your My Cart directory and list all the possible flyers for check out. Select the ones that you want and check out. If you forgot what your flyer looks like, you can conveniently click on the description to get a preview of the flyer to jog your memory. You can also click on the &ldquo;+&rdquo; sign to see the market areas you have selected.</li>
                <li>If that&rsquo;s not enough, we&rsquo;ve added some great stuff to your My Flyers directory. First, we added a Generate HTML button right next to your flyers. You can use the HTML generated code to easily post and enhance your ads craigslist, LiveDeal, eBay and other sites that accept HTML.</li>
                <li>Next is the brand new syndication button. If you would like for us to post your flyer on the popular real estate websites, we are happy to do it. Click on this button and within 48 hours your listing will be in front of millions of potential buyers. (The syndication feature is almost here, but not yet!)</li>
                <li>We&rsquo;ve changed the format of how the flyer is delivered to agents to ensure better delivery and tracking. Agents will now receive a personalized email from you with a short description of your property. They are asked to click on a link to see the flyer details. These attractive messages help ensure less emails go to the Spam file and more to inboxes and it helps us track the success of your flyer. That&rsquo;s right, you can now view how many agents opened your flyer by going to your My Flyers directory and clicking on the analytics link.</li>
                <li>We have added search feature of recent flyers so that potential buyers can now search for properties on our site.</li>
                <li>You will find our New &amp; Updates section. Look to this section to find out about what&rsquo;s new on the site and how to maximize the services we offer.</li>
                <li>You&rsquo;ll notice some really exciting real estate marketing features that we have added and can be accessed from the <%= clsUtility.SiteBrandName %> homepage. They include our new virtual tour site, called HomeTour, that allows you to quickly make professional virtual tours in minutes using standard digital photographs. We transform standard photos into true panoramic visual tours. There is no software to buy or download (or special equipment). It is so simple that we would be surprised if you can&rsquo;t create a great virtual tour in under 15 minutes. Create a virtual tour to use within your flyer, your website or anywhere. You can also track how many people have viewed your visual tour and from where. Now there is no reason why you shouldn&rsquo;t present all your listings in their best light. And, it doesn&rsquo;t hurt to show your client how well you are marketing their property!</li>
                <li>Another exciting sister site, called webposts, helps you create great ads that are posted on leading real estate websites so that buyers can find your listings. You can create stylish flyer ads to post on popular websites like Craigslist or Backpage, or cool looking single property websites. Give it a try and you will be impressed how easy and effective webposts can be.</li>
            </ul>
		</div>
    </div>
</asp:Content>